security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory: { memory: null }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_token:
      pattern: ^/api/token$
      security: false
    api:
      pattern: ^/api
      security: true
      stateless: true
      oauth2: true

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  access_control:
    - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
