security:
  providers:
    user_provider:
      id: 'App\Framework\Component\Security\User\UserProviderImpl'

  encoders:
    App\Entity\Security\User\UserSecurityCredentialImpl:
        algorithm: auto

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_token:
      pattern: ^/oauth2/token$
      security: false
      host: '%api_host%'
    api:
      pattern: ^/(?!oauth2/token).*
      security: true
      stateless: true
      host: '%api_host%'
      oauth2: true

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  access_control:
    - { path: ^/oauth2/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
