trikoder_oauth2:

  authorization_server:
    private_key: '%kernel.project_dir%/var/oauth/private.key'
    private_key_passphrase: null

    encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'
    encryption_key_type: plain

    access_token_ttl: PT1H
    refresh_token_ttl: P1M
    auth_code_ttl: PT10M

    grant_types:
      authorization_code:
        enable: true
        require_code_challenge_for_public_clients: true
      client_credentials:
        enable: true
      implicit:
        enable: false
      password:
        enable: true
      refresh_token:
        enable: true

  resource_server:
    public_key: '%kernel.project_dir%/var/oauth/public.key'

  scopes: [ user_creation, user_basic_profile ]

  persistence:
    doctrine:
      entity_manager: default
