version: '3'

volumes:
    postgres:
        driver: local

services:
    ### PHP-FPM ##############################################
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
                - INSTALL_AMQP= false
                - INSTALL_APCU= true
                - INSTALL_BLACKFIRE= false
                - INSTALL_COMPOSER= true
                - INSTALL_GIT= true
                - INSTALL_INTL= true
                - INSTALL_NODE= true
                - INSTALL_YARN= true
                - INSTALL_PGSQL= true
                - INSTALL_PHPDBG= false
                - INSTALL_PHPREDIS= false
                - INSTALL_SYMFONY= true
                - INSTALL_XDEBUG= true
                - INSTALL_XSL= true
                - LOCALE=POSIX
                - http_proxy
                - https_proxy
                - no_proxy
        volumes:
            - '.:/usr/src/app'
            - ./docker/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        expose:
            - "9000"

    ### NGINX Server #########################################
    nginx:
        image: nginx:alpine
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "80:80"
        depends_on:
            - php-fpm

    ### PostgreSQL ###########################################
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "15432:5432"
