#oauth2:
#  resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'

oauth2_authorize:
  path: /oauth2/authorize
  controller: Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController::indexAction
  methods: GET
  host: '%web_host%'
