nelmio_alice:
    locale: 'fr_FR'
    seed: 1
    functions_blacklist:
        - 'current'
        - 'shuffle'
        - 'date'
        - 'time'
        - 'file'
        - 'md5'
        - 'sha1'
    loading_limit: 5
    max_unique_values_retry: 150
