parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

    bind:
      App\BusinessRules\UseCase $createUser: '@App\BusinessRules\User\UseCases\CreateUser'

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
